### ISSUE TITLE
cannot compile in g++ 4.8.5

### ISSUE THREAD

**Issue by RunningOn** [biojppm/rapidyaml#385]
I try to use the single header file "rapidyaml-0.5.0.hpp" (downloaded from the release assets) in my project, but it gives me an error:

```
.//rapidyaml-0.5.0.hpp:644:2: error: #error "amalgamate: file c4/gcc-4.8.hpp must have been included at this point"
 #error "amalgamate: file c4/gcc-4.8.hpp must have been included at this point"
```

how to fix this? in CentOS 7.6, g++ 4.8.5

**Comment by biojppm** [comment]
possibly related to biojppm/c4core#103

**Comment by biojppm** [comment]
Actually, I think the current master of c4core already fixes this. See biojppm/c4core#106 (merged).

**Comment by biojppm** [comment]
See also #350
