### ISSUE TITLE
gcc 4.8.5 fails to compile

### ISSUE THREAD

**Issue by MountCloud** [biojppm/rapidyaml#350]
rapidyaml.hpp:643:2: error: #error "amalgamate: file c4/gcc-4.8.hpp must have been included at this point"

```
// provided by cmake sub-project
// amalgamate: removed include of
// https://github.com/biojppm/c4core/src/c4/gcc-4.8.hpp
//#               include "c4/gcc-4.8.hpp"
#if !defined(C4_GCC_4_8_HPP_) && !defined(_C4_GCC_4_8_HPP_)
#error "amalgamate: file c4/gcc-4.8.hpp must have been included at this point"
#endif /* C4_GCC_4_8_HPP_ */
````

But this path has not been found：https://github.com/biojppm/c4core/src/c4/gcc-4.8.hpp

**Comment by MountCloud** [comment]
There is also this problem:

rapidyaml.hpp:3272:86: error: reference to ‘max_align_t’ is ambiguous
     void* reallocate(void* ptr, size_t oldsz, size_t newsz, size_t alignment=alignof(max_align_t))

**Comment by MountCloud** [comment]
I made some tweaks to rapidyaml-0.5.0.hpp and it compiles with GCC 4.8.5.

```
1: replace all "alignof(max_align_t)" to "alignof(std::max_align_t)"

2: remove this validation:
#if !defined(C4_GCC_4_8_HPP_) && !defined(_C4_GCC_4_8_HPP_)
#error "amalgamate: file c4/gcc-4.8.hpp must have been included at this point"
#endif /* C4_GCC_4_8_HPP_ */
```

**Comment by biojppm** [comment]
Thanks for reporting. Does this happen in the compiled library too?

It is hard for me to test this. The github runners no longer have support for gcc 4.8. Which distro are you using?

**Comment by MountCloud** [comment]
The version I use:
```
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
I used this method to solve the situation where single header could not compile in GCC 4.8.5.
↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓↓

> I made some tweaks to rapidyaml-0.5.0.hpp and it compiles with GCC 4.8.5.
> 
> ```
> 1: replace all "alignof(max_align_t)" to "alignof(std::max_align_t)"
> 
> 2: remove this validation:
> #if !defined(C4_GCC_4_8_HPP_) && !defined(_C4_GCC_4_8_HPP_)
> #error "amalgamate: file c4/gcc-4.8.hpp must have been included at this point"
> #endif /* C4_GCC_4_8_HPP_ */
> ```
